In [1]:
import pandas as pd
from pandas import json_normalize
import numpy as np

In [2]:
df = pd.read_json('https://raw.githubusercontent.com/sthemonica/alura-voz/main/Dados/Telco-Customer-Churn.json')
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [3]:
# Normalizando as colunas no formado json
custmer_normalize = json_normalize(df.customer)
phone_normalize = json_normalize(df.phone)
intrnet_normalize = json_normalize(df.internet)
account_normalize = json_normalize(df.account)


# Adicionando as colunas ao df antigo
dados = pd.concat([df, custmer_normalize, phone_normalize, intrnet_normalize, account_normalize], axis=1)
dados = dados.drop(columns=['customer', 'phone', 'internet', 'account'])
dados.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [4]:
# Avaliando os tipos dos dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [5]:
dados['Charges.Total']

0         593.3
1         542.4
2        280.85
3       1237.85
4         267.4
         ...
7262      742.9
7263     1873.7
7264      92.75
7265    4627.65
7266     3707.6
Name: Charges.Total, Length: 7267, dtype: object

In [6]:
# Vereficando valores vazios
dados.replace('', np.nan, inplace=True)
dados.replace(' ', np.nan, inplace=True)
dados.isnull().sum()

customerID            0
Churn               224
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
Charges.Monthly       0
Charges.Total        11
dtype: int64

In [7]:
# São 244 observações vazias para o valor de Churn. Verificando esses valores

total_churns_vazios = len(dados[dados['Charges.Total'].isnull()])
total_dados = len(dados)
print('Os churns vazios representam', (total_churns_vazios/total_dados)*100, '%')

Os churns vazios representam 0.15136920324755745 %

In [8]:
# Como os churns são 0.15% do todo, decidi retirar esses valores vazios para não prejudicar as análises
dados_v1 = dados.dropna()

print('Total de dados apos tratamentos:', dados_v1.shape)
print('Total de dados anterior aos tratamentos:', dados.shape)

Total de dados apos tratamentos: (7032, 21)
Total de dados anterior aos tratamentos: (7267, 21)

In [9]:
# Renomenado as colunas
dados_v1.rename(
    columns= {
        'customerID' : 'id_cliente',
        'Churn': 'cancelamento',
        'gender': 'genero',
        'SeniorCitizen' : 'idade_maior_65anos',
        'Partner' : 'tem_parceirx',
        'Dependents': 'tem_dependentes',
        'tenure': 'meses_de_contrato',
        'PhoneService': 'tem_assinatura_telefone',
        'MultipleLines': 'tem_linhas_telefone',
        'InternetService': 'assinatura_provedor_internet',
        'OnlineSecurity': 'assinatura_seguranca_online',
        'OnlineBackup': 'assinatura_backup',
        'DeviceProtection': 'assinatura_protecao_dispositivo',
        'TechSupport': 'assinatutra_suporte_tecnico',
        'StreamingTV': 'assinatura_tv_cabo',
        'StreamingMovies': 'assinatura_streaming',
        'Contract': 'tipo_contrato',
        'PaperlessBilling': 'preferencia_fatura_online',
        'PaymentMethod': 'forma_pagamento',
        'Charges.Monthly': 'total_mensal',
        'Charges.Total': 'total_gasto'
    },
            inplace=True)
print(dados_v1.columns)

Index(['id_cliente', 'cancelamento', 'genero', 'idade_maior_65anos',
       'tem_parceirx', 'tem_dependentes', 'meses_de_contrato',
       'tem_assinatura_telefone', 'tem_linhas_telefone',
       'assinatura_provedor_internet', 'assinatura_seguranca_online',
       'assinatura_backup', 'assinatura_protecao_dispositivo',
       'assinatutra_suporte_tecnico', 'assinatura_tv_cabo',
       'assinatura_streaming', 'tipo_contrato', 'preferencia_fatura_online',
       'forma_pagamento', 'total_mensal', 'total_gasto'],
      dtype='object')

c:\Users\gusta\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [10]:
# Criando variável de gasto diário

dados_v1['gasto_diario'] = dados_v1['total_mensal']/30
dados_v1.head()

C:\Users\gusta\AppData\Local\Temp/ipykernel_9588/2483253221.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_v1['gasto_diario'] = dados_v1['total_mensal']/30

,id_cliente,cancelamento,genero,idade_maior_65anos,tem_parceirx,tem_dependentes,meses_de_contrato,tem_assinatura_telefone,tem_linhas_telefone,assinatura_provedor_internet,...,assinatura_protecao_dispositivo,assinatutra_suporte_tecnico,assinatura_tv_cabo,assinatura_streaming,tipo_contrato,preferencia_fatura_online,forma_pagamento,total_mensal,total_gasto,gasto_diario
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4,2.796667

In [11]:
# Transformando dados categoricos 'Yes' ou 'No' em contínuos 1 ou 0.
dados_v2 = dados_v1.replace(['Yes'], 1).replace(['No'], 0)

# Salvando os dados limpos
dados_v2.to_json('df_clean.json')